---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "<app>"
  # namespace: ""           # Only include Namespace if the user spcified a namespace
  labels:
    app.kubernetes.io/name: <app>
    app.kubernetes.io/version: 1.0.0
automountServiceAccountToken: false
# imagePullSecrets: {}
# secrets: []

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: <app>-allow-access-to-resource  # Use a descriptive name, that summarizes what access this Role provides. use snake-case-syntax 
  # namespace: ""           # Only include Namespace if the user spcified a namespace
  labels:
    app.kubernetes.io/name: <app>
    app.kubernetes.io/version: 1.0.0
rules: [] # Create the required rules
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: <app>-allow-access-to-resource  # Use a descriptive name, that summarizes what access this Role provides. use snake-case-syntax 
  labels:
    app.kubernetes.io/name: <app>
    app.kubernetes.io/version: 1.0.0
rules: [] # Create the required rules

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: <service-account>-grant-<role-name>   # Always name RoleBindings ServiveAccountName-grant-RoleName
  # namespace: ""
  labels:
    app.kubernetes.io/name: <app>
    app.kubernetes.io/version: 1.0.0
roleRef:
  apiGroup: "rbac.authorization.k8s.io"
  kind: "Role" # or ClusterRole
  name: "<app>-allow-access-to-resource"                  # -required-
subjects:
  - kind: "ServiceAccount"
    name: "<app>"
